apiVersion: v1
kind: Namespace
metadata:
  name: cyberco
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: cyberco
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:buster
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: cyberco
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP